FROM openjdk:11
WORKDIR /home/stc3/Desktop/DockerParity/system-run/
ADD parity-system.jar parity-system.jar
ADD system0620.conf system0620.conf
EXPOSE 4000
CMD java -jar parity-system.jar system0620.conf

